Repository cremalab/app-web, pull requests merged in 2019-11, with the labels that each got.

#38 CAW-37: Fix eslint config issue
  package.json
Labels: bug

#41 CAW-3: Update hygen templates
  .loki/reference/chrome_App_Example.png
  .storybook/addons.ts
  .storybook/config.js
  .storybook/config.ts
  .storybook/webpack.config.ts
  _templates/component/new/README.ejs.t
  _templates/component/new/index.ejs.t
  _templates/component/new/index.js
  _templates/component/new/module.ejs.t
  _templates/component/new/module.stories.ejs.t
  _templates/component/new/module.test.ejs.t
  _templates/component/new/prompt.js
  _templates/component/new/stories.ejs.t
  _templates/type/new/index.ejs.t
  _templates/type/new/prompt.js
  _templates/util/new/README.ejs.t
  _templates/util/new/index.ejs.t
  _templates/util/new/module.ejs.t
  _templates/util/new/module.test.ejs.t
  _templates/util/new/prompt.js
  package-lock.json
  package.json
  src/components/App/App.css
  src/components/App/App.stories.tsx
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/App/README.md
  src/components/App/index.ts
  src/components/App/stories.tsx
  src/utils/decoratorCentered/README.md
  src/utils/decoratorCentered/__snapshots__/test.tsx.snap
  src/utils/decoratorCentered/index.tsx
  src/utils/decoratorCentered/test.tsx
Labels: enhancement

#42 CAW-4: Fix coverage
  package.json
Labels: bug

#44 Add test:types script to type check entire project
  package.json
Labels: enhancement

#40 CAW-1: Update dependencies
  .eslintrc.js
  cypress.json
  cypress/integration/sample_spec.js
  package-lock.json
  package.json
Labels: bug, enhancement

#46 Initial GitHub Actions Setup
  .github/workflows/CI.yml
  .travis.yml
  package.json
Labels: enhancement

#47 Update README.md to Add GitHub Actions CI Badge
  README.md
Labels: enhancement
